spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content2?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zxc,./123

#  redis:
#    port: 6379
#    url: 120.79.189.55

mybatis:
  type-aliases-package: com.example.content2.POJO
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
#  security:
#    user:
#      name: admin
#      password: 123456

server:
  port: 8000
  servlet:
    context-path: /content1-2.0


#logging:
#  config: log4j2-spring.xml



# 生产环境

excelTemplate:
  absolutePath: /usr/share/nginx/content2/ExcelTemplate.xls
  indicatedPath: /usr/share/nginx/content2/tempExcel
  serverIp: 120.79.189.55

# 开发环境
#
#excelTemplate:
#  absolutePath: C:/Users/CrazyH/Desktop/ExcelTemplate.xls
#  indicatedPath: C:/Users/CrazyH/Desktop
#  serverIp: 120.79.189.55