# 云服务端
excelTemplate:
  absolutePath: /usr/share/nginx/content2/ExcelTemplate.xls
  indicatedPath: /usr/share/nginx/content2/tempExcel
  serverIp: 120.79.189.55
  sleepTimeKeep: 1000*60*60*5
  outOfDateThreshold: 1000*60*60*24

#云服务端
  redis:
    port: 6300
    host: 127.0.0.1
    password: zxc,./123